//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTracking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductRegisters = new HashSet<ProductRegister>();
        }
        [DisplayName("Ürün ID")]
        public int ProductID { get; set; }
        [DisplayName("Ürün Adý")]
        public string ProductName { get; set; }
        [DisplayName("Ürün Açýklamasý")]
        public string ProductDescription { get; set; }
        [DisplayName("Ürün Tip ID")]
        public Nullable<int> ProductTypeID { get; set; }
        [DisplayName("Stok Durumu")]
        public Nullable<bool> ProductStockState { get; set; }
        [DisplayName("Marka ID")]
        public Nullable<int> BrandID { get; set; }
        [DisplayName("Ürün Kabul Tarihi")]
        public string AcceptDate { get; set; }
        [DisplayName("Ürün Fiyatý")]
        public Nullable<decimal> ProductPrice { get; set; }
        [DefaultValue(0)]
        [DisplayName("Stok Adedi")]
        public Nullable<int> ProductQuantity { get; set; }
        [DisplayName("Satýn Alan Kullanýcý")]
        public Nullable<int> UserID { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRegister> ProductRegisters { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual User User { get; set; }
    }
}
