//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTracking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductRegister
    {
        [DisplayName("Register ID")]
        public int RegisterID { get; set; }
        [DisplayName("User ID")]
        [Required(ErrorMessage = "User is required.")]
        public Nullable<int> UserID { get; set; }
        [DisplayName("Product ID")]
        [Required(ErrorMessage = "Product is required.")]
        public Nullable<int> ProductID { get; set; }
        [DisplayName("Registred Product Count")]
        [Required(ErrorMessage = "Quantity is required.")]
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
