//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductRegisters = new HashSet<ProductRegister>();
        }
    
        public int ProductID { get; set; }
        [DisplayName("Product Name")]
        [Required(ErrorMessage = "Product Name is required.")]
        public string ProductName { get; set; }
        [DisplayName("Product Description")]
        [Required(ErrorMessage = "Product Description is required.")]
        public string ProductDescription { get; set; }
        [DisplayName("Product Type")]
        [Required(ErrorMessage = "Product Type is required.")]
        public Nullable<int> ProductTypeID { get; set; }
        [DisplayName("Stock State")]
        [Required(ErrorMessage = "Product State is required.")]
        public Nullable<bool> ProductStockState { get; set; }
        [DisplayName("Brand ID")]
        [Required(ErrorMessage = "Brand is required.")]
        public Nullable<int> BrandID { get; set; }
        [DisplayName("Accept Date")]
        [Required(ErrorMessage = "AcceptDate is required.")]
        public string AcceptDate { get; set; }
        [DisplayName("Price")]
        [Required(ErrorMessage = "Price is required.")]
        public Nullable<decimal> ProductPrice { get; set; }
        [DisplayName("Quantity")]
        [Required(ErrorMessage = "Quantity is required.")]
        public Nullable<int> ProductQuantity { get; set; }
        [Required(ErrorMessage = "User is required.")]
        public Nullable<int> UserID { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRegister> ProductRegisters { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual User User { get; set; }
    }
}
