//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTracking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductRegister
    {
        [DisplayName("Zimmet ID")]
        public int RegisterID { get; set; }
        [DisplayName("Kullanýcý ID")]
        public Nullable<int> UserID { get; set; }
        [DisplayName("Ürün ID")]
        public Nullable<int> ProductID { get; set; }
        [DisplayName("Zimmetlenen Ürün Sayýsý")]
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
